name: example_web
description: An example on how to use the intl4x package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl4x: 
    path: ../
  js: ^0.7.1

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  lints: ^2.0.0
