name: messages_builder
description: Build the messages for consumption by package:messages
version: 0.3.0-wip
repository: https://github.com/dart-lang/i18n/pkgs/messages_builder

environment:
  sdk: ^3.0.0

publish_to: none

dependencies:
  code_builder: ^4.3.0
  collection: ^1.18.0
  crypto: ^3.0.3
  dart_style: ^2.2.4
  intl: ^0.19.0
  logging: ^1.2.0
  messages:
    path: ../messages
  messages_serializer:
    path: ../messages_serializer
  path: ^1.8.2
  yaml: ^3.1.2
  yaml_edit: ^2.2.1

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
