name: messages_builder
description: Build the messages for consumption by package:messages
version: 0.2.1
repository: https://github.com/dart-lang/i18n/pkgs/messages_builder

environment:
  sdk: ^3.0.0

dependencies:
  build: ^2.3.1
  code_builder: ^4.3.0
  collection: ^1.18.0
  crypto: ^3.0.3
  dart_style: ^2.2.4
  glob: ^2.1.1
  intl: ^0.18.0
  logging: ^1.2.0
  messages: ^0.2.0
  messages_serializer: ^0.2.0
  native_assets_cli: ^0.6.0
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.2.7
  dart_flutter_team_lints: ^2.1.1
  test: ^1.16.0
