name: messages
description: A lightweight modular library for localization (l10n) functionality.
version: 0.3.0-wip
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/messages

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.1
  intl: ^0.19.0
  logging: ^1.2.0
  messages_builder:
    path: ../messages_builder
  native_assets_cli: ^0.8.0
  path: ^1.9.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.0
