name: messages_serializer
description: Serialization of messages for package:messages.
version: 0.3.0-wip
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/messages_serializer

environment:
  sdk: ^3.0.0

publish_to: none

dependencies:
  messages:
    path: ../messages
  intl: ^0.19.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.21.0
