name: messages_serializer
description: Serialization of messages for package:messages.
version: 0.2.0
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/messages_serializer

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  messages: ^0.1.0

dev_dependencies:
  dart_flutter_team_lints: ^2.1.1
  intl: ^0.18.1
  test: ^1.21.0
