name: intl4x
description: >-
  A lightweight modular library for internationalization (i18n) functionality.
version: 0.13.3
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/intl4x
issue_tracker: https://github.com/dart-lang/i18n/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aintl4x

platforms:
  web:
  android:
  ios:
  linux:
  macos:
  windows:

topics:
  - i18n

environment:
  sdk: ^3.9.3

dependencies:
  collection: ^1.19.1
  hooks: ^0.20.4
  icu4x: ^2.1.0-dev.0
  meta: ^1.17.0
  record_use: ^0.4.2
  timezone: ^0.10.1

dev_dependencies:
  args: ^2.7.0
  dart_flutter_team_lints: ^3.5.2
  test: ^1.26.3
