name: intl4x
description: >-
  A lightweight modular library for internationalization (i18n) functionality.
version: 0.9.2-wip
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/intl4x
platforms:
  web:
  android:
  ios:
  linux:
  macos:
  windows:
topics:
  - i18n

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  ffi: ^2.1.0
  js: ^0.7.1
  logging: ^1.2.0
  meta: ^1.12.0
  native_assets_cli: ^0.7.2
  native_toolchain_rust: ^0.1.0-dev.7

dev_dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  dart_flutter_team_lints: ^3.1.0
  test: ^1.22.1
